# Site Settings
title: Conception participative de tableaux de bord dâ€™apprentissage
subtitle: "Atelier EIAH 2021"
email: madjid.sadallah@gmail.com
description: >
  
baseurl: ""
url: "."
twitter_username: smadjid
github_username:  smadjid
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
